
 (()=> {
    
    /**
    * This fucntion find out facebook users 
    * who have liked your page.
    */
   function getPageUsers(){
      
    let usersList = document.querySelectorAll('._3cb8');

    exportPageUsersInfo(usersList);
     

}

/**
 * this function export Page users 
 *  informations in csv format.
 * @param  {[Object]} usersList users list    
 */
function exportPageUsersInfo(usersList){
   
    let csvContent = [['USERNAME','USERID','USERPROFILE'].join(',')];
  
    Object.keys(usersList).forEach(key => {
         
        csvContent +="\r\n"+[usersList[key].innerText,usersList[key].pathname,usersList[key].href].join(',');

         });
        
        
    downloadCsvFile(csvContent);
}

 /**
 * this function download  csv file 
 * generated by exportPageUsersInfo(usersList) .
 * @param  {[Object]} csvContent CSV file content
 */
function downloadCsvFile(csvContent){
  
    let link = document.createElement("a"); 
    link.setAttribute("href", 'data:text/csv;charset=utf-8,%EF%BB%BF'+encodeURIComponent(csvContent));
    link.setAttribute("download", "Page__users__data.csv");
    document.body.appendChild(link);

    link.click();
}

getPageUsers();

})();




